### PR TITLE
Updating dependencies and docker builds

### LINKED ISSUE #448: Retiring Python3.6 support.

### PR DESCRIPTION
**Pull request by chayim**
Updating the dependencies to use the latest redis-py, as well as the docker build to run redis-stack. Along the way, I added iredis as a binary, and changed how things launch, added the python 3.11 trove. Finally, the README was updated to remove the python 3.6 badge, given that the pyproject.toml already deprecated 3.6. closes #448

### CODE REVIEW

**Comment by chayim** [comment]
@laixintao it doesn't look like these changes impact the reasons they're falling. But, I'd love your feedback!

**Comment by laixintao** [comment]
sorry for the late reply.

thank you! looks good.

but can you add Python11 into the CI and remove python3.6?

**Comment by chayim** [comment]
@laixintao There is no python 3.6, we now have 3.11, and 3.12.

**Comment by laixintao** [comment]
The CI failed may be due to you upgraded redis-py.

Let me merge it first then fix the ci later.

**Comment by laixintao** [comment]
Hi @chayim 

sorry seems pendulum didn't support py312 yet, so I have to cancel py312 support for now until pendulum 3 is released.

**Pull request merged**
