### PR TITLE
Add python 3.12 support

### PR DESCRIPTION
**Pull request by deronnax**

### CODE REVIEW

**Comment by deronnax** [comment]
Hmmm, the same pendulum 3.0.0 error than in #482 .

**Comment by laixintao** [comment]
> Hmmm, the same pendulum 3.0.0 error than in #482 .

Seems those locales files were not packaged into pyoxidizer build https://github.com/sdispater/pendulum/tree/master/src/pendulum/locales , I am trying to fix it here https://github.com/laixintao/iredis/pull/484

**Comment by deronnax** [comment]
An idea of why are they needed now?

**Comment by laixintao** [comment]
> An idea of why are they needed now?

Sorry, no, maybe some packaging logic changed in this version, I need more time to debug the packaging system.

**Comment by deronnax** [comment]
Not a problem anymore with #492 .

**Pull request merged**
